### ISSUE TITLE
Extra libraries needed

### ISSUE THREAD

**Issue by william-reed** [rhyst/idasen-controller#1]
Thanks for publishing this - it is working great so far. Just wanted to make note that I needed the following in order to get this working on my Ubuntu 19 install

`sudo apt-get install libdbus-1-dev`

I also noticed that you have a py-cairo requirement in your `requirements.txt` file yet it doesn't seem to be used in the project. To get that to install I had to run `sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev` (but I suspect I may not have needed all of these maybe only the first). Afterwards I realized it doesn't seem to be used for anything anyway so I wound up removing it.

**Comment by rhyst** [comment]
Awesome! I'm glad it's useful for someone else too.

I just tried installing it in a fresh docker container to see what was required and a couple of those pip requirements were not needed 🤦‍♂️ 

The `gatt-python` package requires installing `python3-dbus` library, and I think `libdbus-1-dev` or similar must be a requirement of that. I have updated the REAME to require this as well.
