### ISSUE TITLE
finds desk, but nothing happens

### ISSUE THREAD

**Issue by timokvamme** [rhyst/idasen-controller#11]
When I run it, "python main.py --stand"
it says Scaning, and then Desk Found
Prints "connected + mac address"
then prints the height
and then nothing.

**Comment by rhyst** [comment]
Is it already at the stand height?

**Comment by timokvamme** [comment]
nope,

and python main.py --sit
produces the same issue.
prints height, but then nothing.

**Comment by rhyst** [comment]
What does your `config.yml` file look like?
