### ISSUE TITLE
Can't adjust height with physical button after interrupting script

### ISSUE THREAD

**Issue by backslashV** [rhyst/idasen-controller#13]
Hi,
If in the middle of the script doing sit or stand I press the physical button on the desk, the desk stops moving and any subsequent button press only moves the desk a few milliliters and then stops.

**Comment by rhyst** [comment]
Thanks for the report! I could not exactly reproduce this (I was able to move the desk with the button no matter what) but it was true that the script would hang if movement was interrupted by a button press. 

I've updated the script with a timeout and also an attempt to detect when a button press happens (it reported speed = 0 for me) and stop the script in both case. Let me know if that fixes the issue for you.

**Comment by noxhirsch** [comment]
I could reproduce this issue and for me it's fixed now. Thank you very much! :)

**Comment by rhyst** [comment]
Awesome, I'll close it then :+1:

**Comment by backslashV** [comment]
Appreciate it.
