### ISSUE TITLE
Reducing\changing the speed of the motors before stop.

### ISSUE THREAD

**Issue by Diskinn** [rhyst/idasen-controller#20]
Dear rhyst,

First of all I want to thank you for the amazing project that you did, it is very useful and practical, no needs to buy an additional expensive panel to be able to adjust the height without holding the buttons.

You mention in the Desk Internals, Behaviour section on the main page that "If no move command is received the motors slows down towards the end and then stops".  however my motor seems to not slow down before stop, they just stop very abruptly and it is annoying because the monitor and the speakers on my desk shake a little after such stops. this behavior is not related to your project because I have the same problem no matter if I use windows app or the original panel  that came with the desk to adjust the height.

I was wondering if there is a way to control the speed of the motors with your code to slow down the motors before stop or to just reduce the speed somehow to reduce the stop impact.

Thanks in advance.

**Comment by rhyst** [comment]
I'm very glad it's useful 😊

I can't say for certain but I did not see anything that would control the speed of movement when decompiling the app or when playing with the BLE characteristics. 

I think the behaviour of your desk is the same as mine and the "slowing down" is quite abrupt and results in some shaking. I included that description to indicate that it is possible to send the commands too slowly and then you get repeated jerking.
