### ISSUE TITLE
Slow down the motor by itself at the end avoiding shaking of the desk

### ISSUE THREAD

**Issue by arekm** [rhyst/idasen-controller#25]
My problem is that my heavy monitor shakes a lot when movement stops. It isn't soft stop unfortunately.

I'm reading description and 

````
If no move command is recieved in that second then the motor slows down towards the end and then stops.
If you send a move command late, then there will some stuttering as the desk may have already started
to slow the motors. You can stop the motion part way through by sending a stop command though
it sometimes does not respond immediately. 
````

so I assume that it can be done in a way where motor slows down itself softly, with proper moving commands timing.

This is feature request about implementing such soft stop if possible.

Thanks!

**Comment by rhyst** [comment]
Ah, yeh this is what I suspected. I do not think the Idasen controller actually supports many of the commands/characteristics.
