### ISSUE TITLE
Configurable BaseHeight & MaxHeight

### ISSUE THREAD

**Issue by vniehues** [rhyst/idasen-controller#34]
Hi there, 

I plan to add configurable BaseHeight & MaxHeight to my [HomeBridge Plugin](https://github.com/vniehues/homebridge-linak).
It would be nice if I could pass these values to your idasen-controller. 
The perfect way for me would be with argument flags like these:

`Idasen-controller --move-to 850 --base-height 600 --max-height 1300`

As it stands right now, when I try to send the desk down to lets say 580mm, your script would prevent that (because it's lower than the desk height).

What is your stance on this? 

Edit: I just saw #29 and I think if we could add the max-height as well this could be the perfect solution.

**Comment by vniehues** [comment]
I think this would make your controller compatible with different Linak desks which could have different heights

**Comment by rhyst** [comment]
Hey, I just merged a PR that adds a configurable base height. I will add an option to configure the movement range as well.

**Comment by vniehues** [comment]
Oh no.. we were at it at the same time so I commented on that merged PR. Sorry for that.
Thank your for looking into the movement range! I'm looking forward to integrating it into the plugin :)

**Comment by rhyst** [comment]
subraizada3 added this moments ago. I will make a release soon.
