### ISSUE TITLE
Dockerized version and MQTT wrapper to easily integrate with Home Assistant

### ISSUE THREAD

**Issue by maxime1992** [rhyst/idasen-controller#45]
Hello!

I wanted to say a tremendous THANK YOU for this script :pray:!

I've spent an entire hackday trying to connect to my desk using many libraries... But none of these worked reliably until I found out your project :tada: _(and I didn't want to buy an ESP32 device to get something reliable up and running with https://github.com/j5lien/esphome-idasen-desk-controller)_

My ultimate goal was to be able to have some kind of nice automation built with Home Assistant using the desk (toggle sitting/standing position with an NFC tag, integrate with the crazy good looking [lovelace card](https://github.com/IhorSyerkov/linak-desk-card) and have the desk go up automatically for daily standup :smile:...). Possibilities are really endless with Home Assistant!

The server mode is :fire:! It allows me to keep the connection up and running at all time
- avoiding disconnections
- making the time to respond to a command really fast
- allowing me to send a `monitor` command every minute, which will emit the current desk height, which will make Home Assistant consider that the desk is "connected" properly (by avoiding a timeout)

So thank you very much for the outstanding work :)! 

In case anyone is interested: https://github.com/maxime1992/linak-2-mqtt

**Comment by rhyst** [comment]
Glad it works for you and thanks for the thanks 😄 

I should add a list of projects using this script!
