### ISSUE TITLE
license

### ISSUE THREAD

**Issue by zaunermax** [rhyst/idasen-controller#5]
This is the first project I found, that controls my Idasen desk correctly :raised_hands: Thank's for making this public :rocket: 

I would like to create a simple HTTP server for my smart home system and was wondering what license this project is under and if I could take some of your code to use it in my server implementation?

Adding a license to this project would be great :raised_hands: 

Best regards,
Max

**Comment by rhyst** [comment]
Hey, glad it works it for you!

Added MIT License, do what you want 🚀
