### ISSUE TITLE
Something unexpected went wrong or Address not found

### ISSUE THREAD

**Issue by Or1j1n** [rhyst/idasen-controller#50]
Hi

Issue : 
![image](https://user-images.githubusercontent.com/8409935/181011145-78e1a464-cf96-4093-837b-cfca40511be4.png)
![image](https://user-images.githubusercontent.com/8409935/181012460-1511503b-9bc0-4b7c-80a2-4c3375cbc11a.png)

Pre-requisites : (Windows 10 up to date)

![image](https://user-images.githubusercontent.com/8409935/181015286-d8181a2d-505d-4673-a587-608edb57f67f.png)

![image](https://user-images.githubusercontent.com/8409935/181011206-426cb98c-126b-4a5d-ab50-d9f42d91f9a1.png)

![image](https://user-images.githubusercontent.com/8409935/181011308-804a3234-5d51-415e-b23b-ac76c7eff4e6.png)

![image](https://user-images.githubusercontent.com/8409935/181011397-280e3191-3d33-4131-bf2a-a67b5dabea2b.png)

![image](https://user-images.githubusercontent.com/8409935/181011694-cd711400-06d2-453e-b642-cd2ae55f4fdb.png)

![image](https://user-images.githubusercontent.com/8409935/181012009-379af003-d392-4e4b-8c52-118c2cd08900.png)

Maybe wierd ?
1. If i'm not clicking on the desk bluetooth button (desk not appearing)
![image](https://user-images.githubusercontent.com/8409935/181012186-6a2d1f71-08d5-463e-9884-8736f3c4dda0.png)
2. If i'm clicking on the button (desk appearing)
![image](https://user-images.githubusercontent.com/8409935/181012319-f5633878-009c-4b53-811e-865d1c3eb8e0.png)
3. I dont know if thats expected, but the Desk does not stay connected to the PC. When registering the device, it goes to register->connected->paired

PS : Tried changing to connection_timeout: 30, still not working.

**Comment by rhyst** [comment]
Thank you for the all the details 🙇

Just to confirm, is this an Idasen desk?

I am away for a couple of weeks do I may not be able to be very helpful.

**Comment by Or1j1n** [comment]
> Just to confirm, is this an Idasen desk?
Yes

**Comment by rhyst** [comment]
Is there no error message printed after "Something unexpected went wrong" ?

**Comment by Or1j1n** [comment]
I dont have the issue anymore. Not sure why. But thanks anyway :P
