### ISSUE TITLE
Unable to control Linak Desk - CBD6S Control Unit

### ISSUE THREAD

**Issue by NZVengeance** [rhyst/idasen-controller#59]
I have a desk bought from a commercial furniture here in NZ, they are custom built to the user's requirements. It's not an "off the shelf" unit like an Ikea.

Note: I understand this is not on the list of supported devices. Just hoping there is something I can do to help get support added

The desk is using the following:

- Linak CBD6SP00020A-009 (Controller)
- LINAK DL6101BNE650560 (3-stage lifting column)
- LINAK DPG1C32-000006 (Control)

I have SSH'd into my Homebridge where I have the idasen-controller setup and I tried to move the desk
`stargate@stargate:~ $ idasen-controller --move-to 750
Connected E9:76:49:9A:08:DA
Height:  794mm
Moving to height: 750
Height:  794mm Speed:  0mm/s
Final height:  794mm (Target:  750mm)
Disconnected`

I can also see when using BlueZ that the desk is connected:
`[bluetooth]# paired-devices
Device E9:76:49:9A:08:DA DESK 2266
`

config.yaml
`mac_address: E9:76:49:9A:08:DA
base_height: 690
movement_range: 340
scan_timeout: 5
connection_timeout: 10
movement_timeout: 30
adapter_name: hci0
server_address: "127.0.0.1"
server_port: 9123
favourites:
  sit: 690
  stand: 1030
`
![IMG_7058](https://user-images.githubusercontent.com/12107384/208796644-e1fa5094-4c5e-49d9-b1a2-db841c0b2c71.jpg)
![IMG_7059](https://user-images.githubusercontent.com/12107384/208796650-cec58050-155f-49df-adbd-3691f0b937aa.jpg)
![IMG_7060](https://user-images.githubusercontent.com/12107384/208796655-696bc2e8-b269-4086-8279-dc5882454197.jpg)

**Comment by rhyst** [comment]
I may be wrong but this looks like a duplicated of https://github.com/rhyst/idasen-controller/issues/32

Feel free to reopen if thats not true, but thats where the info about the DPG1C is. The short answer is that I do not have one so can't test anything and it really requires someone who has the desk to play around with the different commands.
