### ISSUE TITLE
Linak CBD6S Controller 

### ISSUE THREAD

**Issue by goldjunge91** [rhyst/idasen-controller#62]
Hi,
i get an lift table with linak motion system and CBD6S Controller on the website they sell for 40€ a bluethooth adapter that says its compatible with my controller unit.
and i'm thinking of to tinker a selfmade Bluethooth / wifi adapter with an esp32 and would ask if its worst the time or not

**Comment by rhyst** [comment]
Sounds like a fun project but I have no idea sorry. Bluetooth LE as a protocol seems relatively simple to use with a library like `bleak` but I don't know what you would need to do on something like an esp32. I also don't know what protocol the Linak hardware uses to communicate over the physical wires in the desk so I can't advise on how easy it will be to integrate with.
